services:
  postgres:
    image: postgres:15
    container_name: qrc_postgres
    environment:
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

volumes:
  qrc_pgdata:
